name: simple_tools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  wheel_chooser: ^1.1.2
  provider: ^6.1.2
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.10
  sqflite_common_ffi: ^2.2.0
  circular_countdown_timer: ^0.2.4
  shared_preferences: ^2.2.2
  flutter_ringtone_player: ^4.0.0+3
  permission_handler: ^11.3.1
  flutter_compass: ^0.8.0
  sensors_plus: ^6.0.1
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  ai_barcode_scanner: ^5.2.2
  image_picker: ^1.1.2
  audioplayers: ^6.1.0
  intl: ^0.18.0
  http:
  qr_flutter: ^4.1.0
  file_picker: ^8.1.3
  barcode_widget: ^2.0.3
  image_gallery_saver: ^2.0.3
  timezone:
  device_info_plus:
  battery_plus:
  network_info_plus:
  package_info_plus:
  system_info2: ^3.0.1
  community_charts_flutter: ^1.0.2
  fl_chart: ^0.69.0
  flutter_background_service: ^5.0.10
  app_settings: ^5.1.1
  usage_stats: ^1.2.0
  device_apps:
  flutter_local_notifications: ^17.2.4
  mobile_scanner: ^5.2.3





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
